"""Store Protocol: storage-agnostic surface for Indexer / Harness / CLI (SPEC-P1 §4).

`Database` (SQLite, P0) and `PgStore` (PostgreSQL, P1) both implement this
surface so the indexer pipeline, harness matching logic and CLI helpers run
unchanged on either backend.  Row shapes returned by every method are
SQLite-compatible dicts (e.g. `meta_json`, `candidates_json`,
`only_names_json`) — each store is responsible for mapping its own
representation onto this canonical shape.

S1 requirement (SPEC-P1 §23): exact canonical identity equivalence — the same
adapter facts must produce identical node/edge id strings on both stores.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Iterable, Optional, Protocol

from .model import Callsite, EdgeSpec, ImportBinding, IncludeBinding, Node
if TYPE_CHECKING:
    from .evidence_authority.support import CanonicalSupportReceipt


class ArchError(Exception):
    """Store-level architecture-plane failure (SPEC-P1 §6.2/§23).

    Raised by both backends as a backstop for DB-enforced invariants
    (composite-FK model isolation, ON DELETE RESTRICT, unique mappings).
    The API layer translates `code` into the unified error envelope.
    """

    def __init__(self, code: str, message: str, details: dict | None = None):
        self.code = code
        self.message = message
        self.details = details or {}
        super().__init__(message)


class FlowError(Exception):
    """Store/service-level software-circuit failure (SPEC-P2 §19/§20).

    Same envelope as ``ArchError``: ``code`` + message + details, translated
    by the API layer into the unified error envelope.  Raised for FK-rule
    backstops and service-level validation (composite hierarchy cycles,
    port direction/semantic mismatches, duplicate port names, ...).
    """

    def __init__(self, code: str, message: str, details: dict | None = None):
        self.code = code
        self.message = message
        self.details = details or {}
        super().__init__(message)


class Store(Protocol):
    """Minimal surface used by rintel's pipeline (see SPEC-P1 §4)."""

    # -- lifecycle ------------------------------------------------------
    def begin(self, repo_id: str | None = None) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def now(self) -> int: ...

    # -- repos / snapshots ---------------------------------------------
    def upsert_repo(self, repo_id: str, root_path: str) -> None: ...
    def repos(self) -> list[dict]: ...
    def repo(self, repo_id: str) -> Optional[dict]: ...
    def new_snapshot(self, repo_id: str, parent_id: str | None,
                     commit: str | None = None,
                     meta: dict | None = None) -> str: ...
    def snapshots(self, repo_id: str) -> list[dict]: ...
    def snapshot(self, sid: str) -> Optional[dict]: ...
    def current_snapshot(self, repo_id: str) -> Optional[str]: ...
    def publish_snapshot(self, repo_id: str, snapshot_id: str) -> None: ...

    # -- files ----------------------------------------------------------
    def upsert_file(self, repo_id: str, path: str, hash_: str, size: int,
                    parser_version: str, indexer_version: str,
                    status: str = "ok",
                    semantic_digest: str | None = None) -> None: ...
    def file_state(self, repo_id: str, path: str) -> Optional[dict]: ...
    def files(self, repo_id: str) -> list[dict]: ...

    # -- nodes ----------------------------------------------------------
    def upsert_node(self, node: Node, repo_id: str,
                    snapshot_id: str) -> tuple[str, bool]: ...
    def node_by_qname(self, repo_id: str, snapshot_id: str,
                      qname: str) -> Optional[dict]: ...
    def node_by_id(self, repo_id: str, snapshot_id: str,
                   nid: str) -> Optional[dict]: ...
    def all_nodes(self, repo_id: str, snapshot_id: str) -> list[dict]: ...
    def nodes_by_path(self, repo_id: str, snapshot_id: str,
                      path: str) -> list[dict]: ...
    def nodes_by_path_prefix(self, repo_id: str, snapshot_id: str,
                             path_prefix: str) -> list[dict]: ...
    def delete_nodes_in_paths(self, repo_id: str, snapshot_id: str,
                              paths: Iterable[str]) -> int: ...
    def delete_nodes_in_paths_except(self, repo_id: str, snapshot_id: str,
                                     paths: Iterable[str],
                                     keep_ids: Iterable[str]) -> int: ...

    # -- edges ----------------------------------------------------------
    def add_edge_raw(self, kind: str, src_id: str, dst_id: str,
                     repo_id: str, snapshot_id: str,
                     confidence: float = 1.0, meta: dict | None = None,
                     evidence: dict | None = None) -> bool: ...
    def edges_for_node(self, repo_id: str, snapshot_id: str, nid: str,
                       direction: str = "both",
                       relation: str | None = None) -> list[dict]: ...
    def delete_edges_in_snapshot(self, repo_id: str, snapshot_id: str,
                                 kinds: Iterable[str]) -> int: ...
    def delete_edges_touching_paths(self, repo_id: str, snapshot_id: str,
                                    paths: Iterable[str]) -> int: ...
    def delete_edges_from_paths(self, repo_id: str, snapshot_id: str,
                                paths: Iterable[str]) -> int: ...
    def delete_edges_all(self, repo_id: str, snapshot_id: str) -> int: ...
    def all_edges(self, repo_id: str, snapshot_id: str) -> list[dict]: ...

    # -- evidence -------------------------------------------------------
    def add_evidence(self, repo_id: str, snapshot_id: str, entity_type: str,
                     entity_id: str, source: str, confidence: float,
                     location: dict | None = None,
                     payload: dict | None = None) -> None: ...
    def evidence_for(self, repo_id: str, snapshot_id: str,
                     entity_id: str) -> list[dict]: ...
    def delete_evidence_all(self, repo_id: str, snapshot_id: str) -> int: ...
    def delete_evidence_in_paths(self, repo_id: str, snapshot_id: str,
                                 paths: Iterable[str]) -> int: ...
    def delete_evidence_owned_by_paths(self, repo_id: str, snapshot_id: str,
                                       paths: Iterable[str]) -> int: ...
    def delete_node_evidence_all(self, repo_id: str,
                                 snapshot_id: str) -> int: ...

    # -- admitted canonical support ------------------------------------
    def add_support_receipt(self, repo_id: str, snapshot_id: str,
                            receipt: CanonicalSupportReceipt) -> None: ...
    def support_receipts(self, repo_id: str, snapshot_id: str,
                         canonical_fact_id: str) -> list[dict]: ...
    def support_receipts_owned_by_paths(self, repo_id: str, snapshot_id: str,
                                        paths: Iterable[str]) -> list[dict]: ...
    def copy_support_receipts(self, repo_id: str, parent_sid: str,
                              sid: str) -> int: ...
    def delete_support_owned_by_paths(self, repo_id: str, snapshot_id: str,
                                      paths: Iterable[str]) -> int: ...
    def prune_orphan_support(self, repo_id: str, snapshot_id: str) -> int: ...
    def unsupported_new_facts(self, repo_id: str, snapshot_id: str,
                              parent_sid: str | None) -> list[str]: ...

    # -- callsites / imports / includes / pending edges -----------------
    def add_callsite(self, cs: Callsite, repo_id: str,
                     snapshot_id: str) -> int: ...
    def all_callsites(self, repo_id: str, snapshot_id: str) -> list[dict]: ...
    def callsites_in_paths(self, repo_id: str, snapshot_id: str,
                           paths: Iterable[str]) -> list[dict]: ...
    def update_callsite(self, cid: int, resolved_node_id: str | None,
                        resolve_kind: str | None, confidence: float | None,
                        edge_id: str | None) -> None: ...
    def callsite_row(self, cid: int) -> Optional[dict]: ...
    def delete_callsites_in_paths(self, repo_id: str, snapshot_id: str,
                                  paths: Iterable[str]) -> int: ...
    def add_import_row(self, imp: ImportBinding, src_qname: str,
                       repo_id: str, snapshot_id: str) -> int: ...
    def all_imports(self, repo_id: str, snapshot_id: str) -> list[dict]: ...
    def imports_in_paths(self, repo_id: str, snapshot_id: str,
                         paths: Iterable[str]) -> list[dict]: ...
    def set_import_external(self, row_id: int) -> None: ...
    def delete_imports_in_paths(self, repo_id: str, snapshot_id: str,
                                paths: Iterable[str]) -> int: ...
    def add_include_row(self, inc: IncludeBinding, repo_id: str,
                        snapshot_id: str) -> int: ...
    def all_includes(self, repo_id: str, snapshot_id: str) -> list[dict]: ...
    def includes_in_paths(self, repo_id: str, snapshot_id: str,
                          paths: Iterable[str]) -> list[dict]: ...
    def set_include_external(self, row_id: int) -> None: ...
    def delete_includes_in_paths(self, repo_id: str, snapshot_id: str,
                                 paths: Iterable[str]) -> int: ...
    def add_pending_edge(self, edge: EdgeSpec, file_path: str,
                         repo_id: str, snapshot_id: str,
                         meta: dict | None = None) -> int: ...
    def all_pending_edges(self, repo_id: str,
                          snapshot_id: str) -> list[dict]: ...
    def pending_edges_in_paths(self, repo_id: str, snapshot_id: str,
                               paths: Iterable[str]) -> list[dict]: ...
    def delete_pending_in_paths(self, repo_id: str, snapshot_id: str,
                                paths: Iterable[str]) -> int: ...
    def resolution_input_count(self, repo_id: str, snapshot_id: str) -> int: ...

    # -- snapshot copy (incremental, spec §26) --------------------------
    def copy_nodes_edges(self, repo_id: str, parent_sid: str,
                         sid: str) -> int: ...
    def copy_callsites(self, repo_id: str, src_sid: str, dst_sid: str) -> int: ...
    def copy_imports(self, repo_id: str, src_sid: str, dst_sid: str) -> int: ...
    def copy_includes(self, repo_id: str, src_sid: str, dst_sid: str) -> int: ...
    def copy_pending_edges(self, repo_id: str, src_sid: str,
                           dst_sid: str) -> int: ...
    def copy_evidence(self, repo_id: str, src_sid: str, dst_sid: str) -> int: ...
    def copy_unresolved(self, repo_id: str, src_sid: str, dst_sid: str) -> int: ...
    def delete_unresolved_in_paths(self, repo_id: str, snapshot_id: str,
                                   paths: Iterable[str]) -> int: ...

    # -- unresolved / telemetry -----------------------------------------
    def add_unresolved(self, repo_id: str, snapshot_id: str, kind: str,
                       detail: dict) -> None: ...
    def unresolved_count(self, repo_id: str, snapshot_id: str) -> int: ...
    def telemetry(self, run_id: str, repo_id: str | None,
                  language: str | None, phase: str, key: str,
                  value: Any) -> None: ...

    # -- queries --------------------------------------------------------
    def search(self, repo_id: str, query: str, limit: int = 50,
               snapshot_id: str | None = None) -> list[dict]: ...
    def neighbors(self, repo_id: str, snapshot_id: str, nid: str,
                  relation: str | None = None, depth: int = 1,
                  max_nodes: int = 300, direction: str = "both") -> dict: ...
    def stats(self, repo_id: str, snapshot_id: str | None = None) -> dict: ...
    def snapshot_diff(self, repo_id: str, s1: str, s2: str) -> dict: ...
    def view_export(self, repo_id: str, snapshot_id: str,
                    view: str = "all", max_edges: int = 1000) -> dict: ...

    # -- architecture plane (S3, SPEC-P1 §6.2 / §23) --------------------
    # Rows are SQLite-shaped dicts; JSON payloads (layout) are parsed dicts.
    # ids are uuid strings on both backends.
    def arch_workspaces(self) -> list[dict]: ...
    def arch_workspace(self, workspace_id: str) -> Optional[dict]: ...
    def arch_create_workspace(self, repo_id: str, name: str,
                              description: str = "") -> dict: ...
    def arch_models(self, workspace_id: str) -> list[dict]: ...
    def arch_model(self, workspace_id: str,
                   model_id: str) -> Optional[dict]: ...
    def arch_model_baseline(self, workspace_id: str,
                            model_id: str) -> Optional[dict]:
        """Frozen fork baseline (R2): ``{baseline: dict,
        baseline_schema_version: int, base_evidence_snapshot_id}`` or None
        when the model has no baseline (plain AS-IS)."""
        ...
    def arch_fork_model(self, workspace_id: str, source_model_id: str,
                        name: str, description: str = "") -> dict:
        """R2 fork: deep-copy a model into a new proposal in one transaction,
        freezing ``baseline_json`` (schema_version=1) +
        ``base_evidence_snapshot_id``; copied components carry ``origin_id``.
        Copies the AS-IS layout over (UI convenience).  Raises ArchError
        ``model_not_found`` / ``fork_source_not_as_is`` as a backstop."""
        ...
    def arch_components(self, workspace_id: str,
                        model_id: str) -> list[dict]: ...
    def arch_component(self, workspace_id: str, component_id: str,
                       model_id: str | None = None) -> Optional[dict]: ...
    def arch_component_children(self, workspace_id: str,
                                component_id: str) -> list[dict]: ...
    def arch_create_component(self, workspace_id: str, model_id: str,
                              kind: str, name: str, description: str = "",
                              parent_id: str | None = None) -> dict: ...
    def arch_update_component(self, workspace_id: str, model_id: str,
                              component_id: str, *,
                              kind: str | None = None,
                              name: str | None = None,
                              description: str | None = None,
                              parent_id: str | None = None,
                              clear_parent: bool = False,
                              sort_order: int | None = None) -> dict: ...
    def arch_batch_component(self, workspace_id: str, model_id: str,
                             kind: str, name: str, description: str,
                             parent_id: str | None,
                             entities: list[tuple[str, str, str]]) -> dict: ...
    def arch_delete_component(self, workspace_id: str, model_id: str,
                              component_id: str,
                              subtree: bool = False) -> dict: ...
    def arch_relations(self, workspace_id: str,
                       model_id: str) -> list[dict]: ...
    def arch_relation(self, workspace_id: str, relation_id: str,
                      model_id: str | None = None) -> Optional[dict]: ...
    def arch_relations_touching(self, workspace_id: str,
                                component_id: str) -> list[dict]: ...
    def arch_create_relation(self, workspace_id: str, model_id: str,
                             kind: str, src_id: str, dst_id: str,
                             label: str | None = None) -> dict: ...
    def arch_update_relation(self, workspace_id: str, model_id: str,
                             relation_id: str, *,
                             kind: str | None = None,
                             label: str | None = None,
                             clear_label: bool = False) -> dict: ...
    def arch_delete_relation(self, workspace_id: str,
                             relation_id: str) -> None: ...
    def arch_mappings(self, workspace_id: str,
                      model_id: str) -> list[dict]: ...
    def arch_mappings_for_component(self, workspace_id: str,
                                    component_id: str) -> list[dict]: ...
    def arch_batch_mappings(self, workspace_id: str, component_id: str,
                            entities: list[tuple[str, str, str]]) -> list[dict]: ...
    def arch_delete_mapping(self, workspace_id: str,
                            mapping_id: str) -> None: ...
    def arch_mapping_exists(self, workspace_id: str, component_id: str,
                            entity_type: str, entity_id: str) -> bool: ...
    def arch_layout(self, workspace_id: str,
                    model_id: str) -> Optional[dict]: ...
    def arch_put_layout(self, workspace_id: str, model_id: str,
                        layout: dict,
                        expected_updated_at: int | None = None) -> int: ...

    # -- software circuit plane (P2-FLOW0, SPEC-P2 §3/§19) ---------------
    # Renderer-neutral netlist rows (SQLite-shaped dicts).  Ids are uuid
    # strings on both backends.  FK rules are DB-enforced (composite FKs):
    # Port -> Block, Net endpoints -> same FlowModel, Block parent -> same
    # FlowModel; hierarchy cycles are service-level (SPEC-P2 §19).
    def flow_models(self, repo_id: str | None = None) -> list[dict]: ...
    def flow_model(self, flow_id: str) -> Optional[dict]: ...
    def flow_create_model(self, repo_id: str, name: str, snapshot_id: str, *,
                          workspace_id: str | None = None,
                          architecture_model_id: str | None = None,
                          scope_symbol_id: str | None = None,
                          meta: dict | None = None) -> dict: ...
    def flow_update_model(self, flow_id: str, *, name: str | None = None,
                          status: str | None = None,
                          root_block_id: str | None = None,
                          meta: dict | None = None) -> dict: ...
    def flow_blocks(self, flow_id: str) -> list[dict]: ...
    def flow_block(self, flow_id: str, block_id: str) -> Optional[dict]: ...
    def flow_create_block(self, flow_id: str, *, kind: str, name: str,
                          state: str = "proposed",
                          parent_block_id: str | None = None,
                          code: str | None = None,
                          meta: dict | None = None) -> dict: ...
    def flow_update_block(self, flow_id: str, block_id: str, *,
                          name: str | None = None,
                          kind: str | None = None,
                          state: str | None = None,
                          parent_block_id: str | None = None,
                          clear_parent: bool = False,
                          code: str | None = None,
                          meta: dict | None = None) -> dict: ...
    def flow_delete_block(self, flow_id: str, block_id: str) -> None: ...
    def flow_ports(self, flow_id: str) -> list[dict]: ...
    def flow_port(self, flow_id: str, port_id: str) -> Optional[dict]: ...
    def flow_create_port(self, flow_id: str, *, block_id: str, name: str,
                         direction: str, semantic_kind: str,
                         code_type: str | None = None,
                          position_order: int | None = None,
                         meta: dict | None = None) -> dict: ...
    def flow_update_port(self, flow_id: str, port_id: str, *,
                         name: str | None = None,
                         semantic_kind: str | None = None,
                         code_type: str | None = None,
                         clear_type: bool = False,
                         position_order: int | None = None) -> dict: ...
    def flow_delete_port(self, flow_id: str, port_id: str) -> None: ...
    def flow_nets(self, flow_id: str) -> list[dict]: ...
    def flow_create_net(self, flow_id: str, *, source_port_id: str,
                        target_port_id: str, kind: str = "control",
                        label: str | None = None,
                        meta: dict | None = None) -> dict: ...
    def flow_delete_net(self, flow_id: str, net_id: str) -> None: ...
    def flow_bindings(self, flow_id: str) -> list[dict]: ...
    def flow_put_binding(self, flow_id: str, *, block_id: str,
                         snapshot_id: str, canonical_symbol_id: str,
                         binding_kind: str = "implementation") -> dict: ...
    def flow_clear_binding(self, flow_id: str, block_id: str) -> None: ...
    def flow_layout(self, flow_id: str) -> Optional[dict]: ...
    def flow_put_layout(self, flow_id: str, layout: dict) -> int: ...

    # -- evidence lookups for arch mapping validation/resolution ---------
    def entity_exists(self, repo_id: str, snapshot_id: str,
                      entity_type: str, entity_id: str) -> bool: ...
    def entity_row(self, repo_id: str, snapshot_id: str,
                   entity_type: str, entity_id: str) -> Optional[dict]: ...
