"""FLOW-INFER0 endpoints (derived Flow projection, read-only).

Serves the deterministic flow artifacts generated by
rintel.flow_infer.projector from the frozen FAC lane + the real source.
No analysis, no mutation; everything is DERIVED (flow ≠ evidence, FI1).
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from fastapi import APIRouter, HTTPException

TOURNAMENT = Path(__file__).resolve().parents[4] / "analysis_tournament" / "flow_infer"

ARTIFACTS = (
    "entrypoints", "dispatch", "master_flow", "scenarios",
    "regions", "membership", "manual_audit", "unit_summary",
)

router = APIRouter(prefix="/flow-infer", tags=["flow-infer"])


def _artifact(name: str) -> Path:
    p = TOURNAMENT / f"fac_{name}.json"
    if not p.exists():
        raise HTTPException(status_code=404, detail={
            "code": "flow_infer_artifact_not_found",
            "message": f"flow-infer artifact '{name}' is not generated yet",
            "details": {"artifact": name},
        })
    return p


@router.get("")
def index() -> dict:
    return {"items": list(ARTIFACTS), "total": len(ARTIFACTS)}


@lru_cache(maxsize=16)
def _load(name: str) -> dict:
    return json.loads(_artifact(name).read_text())


@router.get("/{artifact}")
def artifact(artifact: str) -> dict:
    if artifact not in ARTIFACTS:
        raise HTTPException(status_code=404, detail={
            "code": "flow_infer_artifact_unknown",
            "message": f"unknown flow-infer artifact '{artifact}'",
            "details": {"artifact": artifact, "known": list(ARTIFACTS)},
        })
    return _load(artifact)
